# define fmod(x,y) (x)
# define pow(x,y) (x)
# define log10(x) (x)
# define floor(x) (x)
# define ceil(x) (x)
# define isinf(x) 0
# define isnan(x) 0
# define isfinite(x) 0
# define signbit(x) 0
# define INFINITY LONG_MAX
# define NAN (-1)
